### ISSUE TITLE
Some videos are going to the folder of the main.py

### ISSUE THREAD

**Issue by MisterEight** [Psycoguana/SubredditMediaDownloader#7]
Instead of the videos going to the folder specified for download, some files are going to the main.py folder.

**Comment by Psycoguana** [comment]
Hey!

Are the files videos or images? Do the files have "temp" in the name?

**Comment by MisterEight** [comment]
> 

The files are videos, they have temp in the name

**Comment by MisterEight** [comment]
For what i can see when the script don't find the PATH for the download folder, the videos goes to the main.py folder, but some videos goes to the right path and some don't.

**Comment by MisterEight** [comment]
![image](https://user-images.githubusercontent.com/103611605/203841982-f8461b9f-a5f0-474c-86cd-5a8bae444e44.png)
O sistema não pode encontrar o arquivo especificado = The system cannot find the specified file

**Comment by Psycoguana** [comment]
Do you have ffmpeg installed? It's a recently added dependency

**Comment by MisterEight** [comment]
![image](https://user-images.githubusercontent.com/103611605/203851069-c4449468-cc48-4589-ba1d-91efe4fb7d6d.png)
Yes i have it

**Comment by MisterEight** [comment]
> Do you have ffmpeg installed? It's a recently added dependency

Also the files have temp in the name, i typed wrong on the comment above

**Comment by MisterEight** [comment]
I think i know my issue, i forgot to rerstat my pc after installing ffmepg, my bad.

**Comment by Psycoguana** [comment]
Awesome, glad it's working now!
