### ISSUE TITLE
The API did a update

### ISSUE THREAD

**Issue by MisterEight** [Psycoguana/SubredditMediaDownloader#8]
I not sure if you know that the PushShift API did update and now the script is not working properly, at least in my machine.
![image](https://user-images.githubusercontent.com/103611605/210559411-1d6a9138-cf88-4c35-bc13-4a1b401ac51a.png)

**Comment by MisterEight** [comment]
https://github.com/seanbreckenridge/pushshift_comment_export/issues/2

**Comment by Psycoguana** [comment]
Hey, thanks a lot for opening the issue! I didn't know about the update. I'll push a fix as soon as possible

**Comment by Psycoguana** [comment]
Took a while, but it's fixed! 😁
